c0re100/qBittorrent-Enhanced-Edition

src/app/main.cpp
Multiple instances can be isolated by the command line argument ```--configuration=<conf>```, so there's no need to stop users from running multiple instances.
=> Allow multiple qB instances

.travis.yml
添加构建AppImage的构建脚本，使用travis-ci构建。效果预览: https://github.com/abcfy2/qBittorrent-Enhanced-Edition/releases/tag/v4.1.8.2-2
TODO:
- desktop集成
- 关联支持
- 自动更新支持
> **已知问题**: 如果启用了托盘图标，会报错: QSystemTrayIcon::setVisible: No Icon set，这个问题似乎是官方使用了图标的绝对路径导致的，因为我发现只有--prefix=/usr的编译参数才能准确显示托盘图标，其余所有的prefix都会导致这个问题，当然打包到AppImage更是如此，它的运行路径根本不是/usr。已经给上游提交了issue: qbittorrent#11366 ，但是官方没有回应我，不知道 @c0re100 是否有解决方案？
=> Add .travis.yml to build AppImage

.travis.yml, README.md
解决 #58 中 AppImage 托盘图标不显示的问题。
README中添加AppImage的下载链接
=> Fix AppImage lost systray icon. #58

.travis.yml
Ubuntu的qt ppa有更新，使用目前最新的LTS版本编译AppImage
=> Upgrade AppImage build with qt 5.12.6

.travis.yml
看上游新版本快发布了，4.2.2版本的issue快close完了。顺势更新一波AppImage的编译依赖
=> Upgrade appimage build deps

.travis.yml
找到一个ppa: savoury1/backports，可以将Ubuntu 16.04的底层编译类库进行升级。这样一来基本上编译AppImage的时候使用的都是最新版本的类库了。
关于信息中显示的编译信息如下：
```
Qt: 5.14.1
Libtorrent: 1.2.4.0
Boost: 1.70.0
OpenSSL: 1.1.1d
zlib: 1.2.11
```
我本地运行了一下，基本上没啥问题: https://github.com/abcfy2/qBittorrent-Enhanced-Edition/releases/download/v4.2.1.11-1/qBittorrent-Enhanced-Edition.AppImage
=> Add ppa:savoury1/backports for building AppImage

src/app/application.cpp
I just want a torrent client that will handle argument correctly and safely. However, upstream seems not interested in my patch. 
[https://github.com/qbittorrent/qBittorrent/pull/12392](https://github.com/qbittorrent/qBittorrent/pull/12392)
[https://github.com/qbittorrent/qBittorrent/issues/12367](https://github.com/qbittorrent/qBittorrent/issues/12367)
=> Fix arguments handling in "Run external program on torrent completion"

.travis.yml
上游已经修复了linuxdeploy构建AppImage失败的问题，所以提交PR，顺便升级下相关的构建依赖
=> AppImage upgrade libboost to 1.74

.github/workflows/build_and_release.yml
改用github action做CI，以后应该不需要再改动.travis-ci了，防止跟上游冲突。
可以考虑直接停用旧的travis-ci。直接在travis-ci.com网站设置中，取消qBittorrent-Enhanced_Edition的持续集成即可，或者干脆删掉.travis-ci.yml文件也行。
另外可以整理下其他操作系统的构建脚本与步骤，考虑如何自动化，我看github action支持windows和Macos做构建环境，理论上可以在CI同时构建三个平台的二进制包，可以考虑下，整理下相关的脚本，以后加到github action就可以了
=> Add github action

.github/workflows/build_and_release.yml
编译去掉了ICU依赖，减少了nox-static的体积。
加入了交叉编译的构建，目前可以构建出arm/aarch64/mips/mipsel/mips64架构的程序（arm和aarch64手头有设备，可以测试通过，mips系列手头暂时没有真机，期待有人能帮忙测试）
为防止某些情况下可执行程序会被浏览器拦截或者被某些安全查杀所拦截，release发布采用打包zip的方案，既可以压缩体积，也可以保住权限，基本上不会被拦截
=> Add cross compile for some other platforms release

.github/workflows/build_and_release.yml
qt上游已经更新了6.0.0-beta的tag。所以调整了qt_tag的获取算法，目前配置为`5`版本的最新稳定版本。
=> Pin qt version for building

.github/workflows/build_and_release.yml, src/base/bittorrent/peer_blacklist.hpp, src/base/bittorrent/peer_filter_plugin.hpp, src/base/bittorrent/peer_logger.hpp, src/base/bittorrent/peerinfo.cpp, src/base/bittorrent/peerinfo.h, src/base/bittorrent/session.cpp, src/base/bittorrent/session.h, src/src.pro, src/webui/api/transfercontroller.cpp, src/webui/api/transfercontroller.h
first of all, I liked features provided by this qBittorrent variant, but I think their implementation is far to be optimal. this pull request suggest much more simpler (and cleaner) implementation of peer filtering feature (that's why I found that project).
firstly, few words about currently existing logic. some timer periodically gets list of all connected peers from all torrents and then bans some of them depending on settings and rules. peer ban is achieved by adding "bad peer" IP to libtorrent peer blacklist. this is very inconvenient and expensive: get (and copy) list of already banned IPs known to libtorrent, add new IP (this can cause memory re-allocate operation), and then return modified list to libtorrent (very likely another copy is happen). moreover, iterating over thousands …
=> reimplemented "ban bad peers" feature

.github/workflows/build_and_release.yml
use only first link from boost download page in case few links were parsed (for example, beta release is available)
completely fixes CI builds (I [enabled GitHub Actions in my fork](https://github.com/Kolcha/qBittorrent-Enhanced-Edition/actions) to test it)
=> improved expression for boost url fetching

src/base/bittorrent/peer_filter_plugin.hpp
I discovered new implementation(ban bad peers plugin) can consume lots of CPU resources.
Since each connection has been exchange Peer ID and libtorrent will parse the client name on handshake stage.
So we can remove `on_interested/on_have....`checking handlers.
high CPU usage (when session have many connections, ~800 on my test):
After remove (~600 connections):
Please feel free to test and post your test result here.
=> Fix high CPU usage

.github/workflows/build_and_release.yml, .github/workflows/build_appimage.sh, .github/workflows/cross_build.sh
重构整个构建脚本，将CI的配置部分和构建部分独立，这样方便本地调试和测试，单独运行sh脚本即可。
将整个工件制品的构建分为`build_appimage.sh`和`cross_build.sh`两部分，其中`build_appimage.sh`使用`ubuntu:16.04` docker镜像构建，用于构建AppImage，`cross_build.sh`使用`alpine:latest` docker镜像构建，用于交叉编译qbittorrent-nox。删除了原本的单独构建Linux平台的nox任务，合并到了`cross_build.sh`
重构后的脚本复用性会更好一些，依托于`musl.cc`的各种交叉工具链，理论上可以编译出更多平台的制品，不过交叉编译Windows的还有一些问题待解决，暂时不会在CI中构建Windows制品。
另外加入了`upload-artifacts`功能，构建产生的制品同时也托管于`Actions`页面中的`Artifacts`中，这样以后每次自动触发build都会在Artifacts列表中看到构建后的制品，便于下载和调试，不用每次都得Release才能看到构建制品。
=> refactor artifacts build scripts

src/base/bittorrent/peer_blacklist.hpp, src/base/bittorrent/peer_filter_plugin.hpp, src/base/bittorrent/peer_logger.hpp
- drop useless peer plugin factory class, created simple factory function instead
- don't use QSqlTableModel for db access, used QSqlQuery instead, this will save some memory (why to keep all records contain banned peers info in memory? let's just write them to db and forget!)
no any logic neither db structure changes were made, just small refactoring and cleanup. these changes are result of heavy testing of 'peer whitelist' feature I'm working on for my server. very likely I'll share it later (it is still not ready and have to be polished).
moreover, during this experiments/implementation I found QSqlTableModel unreliable and behave unexpectedly comparing for other 'out of the box' models, so I decided do not use it and use simple queries like in Python. this also decreased the count of …
=> peer filtering refactor and cleanup

.github/workflows/build_and_release.yml, .github/workflows/build_appimage.sh, .github/workflows/cross_build.sh
AppImage 改到VM直接build，以规避 linuxdeploy 在docker环境下运行目前的各种BUG(比如这个 https://github.com/linuxdeploy/linuxdeploy/issues/154 )。
手打一些补丁，以便于x86_64-w64-mingw32 可以正常构建，但是目前似乎没什么卵用，因为qbittorrent-nox似乎对Windows的terminal并没有什么适配，在终端运行会无法看到输出，实际程序是已经在后台运行的，在wine环境下无此问题。暂时先保留这个构建吧，说不定未来qbittorrent-nox官方支持windows环境就可以直接用了
=> Fix AppImage build and add x86_64-w64-mingw32 build

.github/workflows/build_appimage.sh, .github/workflows/cross_build.sh
修复发布构建。不过file_health check这一项不是我的问题。
另外上游似乎对automake构建方式不再维护了，上游推荐采用cmake的构建，下次更新的时候考虑修改这个构建方案。一直觉得cmake交叉编译不如automake方便，一直不怎么喜欢cmake的搞法
=> Fix release build. Fix #212

src/base/bittorrent/peer_blacklist.hpp, src/base/bittorrent/peer_logger.hpp
it doesn't change any behavior, it is just some cleanup:
- do not create std::string with peer id in filters
- do not do substr() in logger, directly create string instead
- moved peer_logger_singleton to peer_logger.hpp
first 2 points should slightly affect performance, because it decreases number of memory allocations (and copy operations) during string creation and std::string -> QString conversions. memory allocations are heavy, and due to places where they happen, a lot of such operations are executed even in small interval (especially when a lot of torrents are active or torrents are very popular), so these small changes can noticeable decrease CPU usage (few percents) or at least decrease memory fragmentation and filter function execution time.
the last point is mostly cosmetic, …
=> peer blacklist optimizations and cleanup

src/base/bittorrent/peer_logger.hpp
- do use AUTOINCREMENT keyword, use available INTEGER PRIMARY KEY, it has "autoincrement feature" out of the box
- use BLOB type for peer id, this is more correct - we store bytes, and it doesn't add any restrictions to data type
- require client and peer id columns to be NOT NULL
these changes does NOT affect any existing users (database already created and table has some data), any existing database will be used as is, because table structure was not changed
changes were tested in both scenarios: db from previous version exits and completely fresh run (no db exists)
=> improved peer logger table creation statement

src/base/bittorrent/peer_blacklist.hpp, src/base/bittorrent/peer_logger.hpp, src/base/bittorrent/session.cpp, src/base/bittorrent/session.h
- fixed initialization order '-Worder'
- added missed headers detected by static analyzers
mentioned issues were found during build on macOS
=> fixed few warnings

src/base/bittorrent/peerinfo.cpp, src/gui/properties/peerlistwidget.cpp, src/webui/api/synccontroller.cpp
- do not do substring operations where peer ID is required
- create peer ID string from first 8 bytes of peer ID buffer
- return empty string when peer ID is not known yet
this avoids a lot of unnecessary memory copies and allocations
also prevents various GUI artifacts caused by zero-bytes strings:
- abnormal row height in peers list on macOS
- square symbols in peer ID column on Linux
no changes (v4_3_x as is):
with changes:
=> improved peerID() implementation

src/base/bittorrent/peer_blacklist.hpp, src/base/bittorrent/peer_filter_plugin.hpp, src/base/bittorrent/peer_whitelist.hpp
official 4.3.x already has libtorrent 2.0 support, but custom filter extensions (blacklist/whitelist) presented here relied on libtorrent 1.2.x API. fortunately the fix is very simple, and it was picked from official qbittorrent 4.3.x branch.
P.S> from my personal experience, it is completely safe to use libtorrent 2.0 now, qBittorrent already supports it, there were only few issues regarding libtorrent 2.0 on their GitHub page. moreover, even in case of rollback to 1.2.x there is nothing required - lt 1.2 successfully reads .fastresume data saved by lt 2.0, so backward compatibility is present "out of the box".
upgrade to lt 2.0 also does not require any heavy migration process (very likely nothing happens at all) - all existing .fastresume data saved by lt 1.2 successfully loaded. …
=> prepare custom filter extensions for libtorrent 2.0

src/base/CMakeLists.txt, src/base/bittorrent/peer_blacklist.hpp, src/base/bittorrent/peer_filter.hpp, src/base/bittorrent/peer_whitelist.hpp, src/base/bittorrent/session.cpp
added custom peer blacklist support as counterpart of previously added in #238 peer whitelist.
closes #190 , closes #223 , closes #226 , closes #248 , closes #51 ,
very likely few more issues can be listed here, but it is pretty hard to me to find them...
blacklist rules are placed in external file 'peer_blacklist.txt', located in qBittorrent data directory ($HOME/.local/share/qBittorrent in case of Linux). if there is NO such file plugin is not activated. it is completely safe to keep empty file - this just means "nothing blacklisted". the same rules syntax and logic are used as for whitelist, but just for blacklisting.
for example, to blacklist client mentioned in #190 , next line can be added to blacklist:
```
-GT\d{4}-    .*
```
in this case `.*` means "any client name", i.e. "ban …
=> peer blacklist

.github/workflows/build_and_release.yml, .github/workflows/build_appimage.sh, .github/workflows/cross_build.sh, README.md
Rename AppImage filename to `qBittorrent-Enhanced-Editon-x86_64.AppImage` to fix zsync update information filename wrong.
=> fix zsync Filename entity for AppImage

.github/workflows/build_appimage.sh
Since cmake 3.23.0, will install lib to /usr/local/lib/x86_64-linux-gnu/ on Debian/Ubuntu by default, so fix this issue.
=> fix appimage build
